[package]
name = "paddy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.16.2"
